spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/user_service_db
    username: bankapp
    password: password
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: kafka:9092
    properties:
      schema.registry.url: http://schema-registry:8081 # Внутри Docker сети
server:
  port: 8080