spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/user_service_db
    username: bankapp
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    user: bankapp
    password: password
  kafka:
    bootstrap-servers: localhost:29098
    properties:
      schema.registry.url: http://localhost:8081 # Для локального запуска
  data:
    redis:
      host: localhost
      port: 6380


server:
  port: 8088
