# ===================================
#      ОБЩИЕ НАСТРОЙКИ
# ===================================
spring:
  application:
    name: analytics-service
  profiles:
    default: local
  kafka:
    consumer:
      group-id: analytics-service-group
      auto-offset-reset: earliest
server:
  port: 8086
logging:
  level:
    root: INFO
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
