spring:
  datasource:
    url: jdbc:clickhouse://localhost:8123/default
    username: default
    password: ""
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
  kafka:
    bootstrap-servers: localhost:29098
server:
  port: 8086

management:
  otlp:
    endpoint: http://localhost:4318
    metrics:
      export:
        url: ${management.otlp.endpoint}/v1/metrics
    tracing:
      export:
        url: ${management.otlp.endpoint}/v1/traces