spring:
  datasource:
    url: jdbc:clickhouse://clickhouse:8123/default
    username: default
    password: ""
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
  kafka:
    bootstrap-servers: kafka:9092
server:
  port: 8080