spring:
  datasource:
    url: jdbc:clickhouse://localhost:8123/default
    username: default
    password: ""
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
  kafka:
    bootstrap-servers: localhost:29098
server:
  port: 8086