spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/history_service_db
    username: bankapp
    password: password
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:29098