# ===================================
#      ОБЩИЕ НАСТРОЙКИ
# ===================================
spring:
  application:
    name: api-gateway
  profiles:
    default: local
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
