spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Включаем автоматическое обнаружение сервисов
          lower-case-service-id: true
  data:
    redis:
      host: redis
      port: 6379
management:
  otlp:
    endpoint: http://alloy:4318
    metrics:
      export:
        url: ${management.otlp.endpoint}/v1/metrics
    tracing:
      export:
        url: ${management.otlp.endpoint}/v1/traces