spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/account_service_db
    username: bankapp
    password: password
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: kafka:9092
management:
  otlp:
    endpoint: http://alloy:4318
    metrics:
      export:
        url: ${management.otlp.endpoint}/v1/metrics
    tracing:
      export:
        url: ${management.otlp.endpoint}/v1/traces