spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/account_service_db
    username: bankapp
    password: password
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: kafka:9092
server:
  port: 8080